In [1]:
import numpy as np
a = np.array([2,3,4], dtype=np.int32)

In [2]:
a

array([2, 3, 4], dtype=int32)

In [4]:
a = np.array([[1,2,3],[2,3,4]])

In [5]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [6]:
a = np.zeros((2, 4))

In [7]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
a = np.ones((3, 4), dtype=np.int)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [10]:
a = np.arange(1, 10 ,2)
a

array([1, 3, 5, 7, 9])

In [11]:
a = np.array([2,3,4],dtype=np.int32)
a

array([2, 3, 4], dtype=int32)

In [12]:
print(a.ndim)
print(a.shape)
print(a.size)

1
(3,)
3


In [14]:
a = np.array([1,2,3,4])
b = np.arange(4)
c1 = a-b
c2 = a*b
c3 = a.dot(b)
c4 = b**2
c5 = np.sin(a)
print(b)
print(c1)
print(c2)
print(c3)
print(c4)
print(c5)

[0 1 2 3]
[1 1 1 1]
[ 0  2  6 12]
20
[0 1 4 9]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [16]:
a = np.array([[1,1], [0,1]])
b = np.arange(4).reshape((2,2))
c1 = a.dot(b)
print(b)
print(c1)

[[0 1]
 [2 3]]
[[2 4]
 [2 3]]


In [20]:
a = np.random.random((2,4))
print(np.sum(a))
print(np.min(a))
print(np.mean(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

[[0.85186166 0.70560655 0.48751838 0.88527106]
 [0.30411265 0.15708586 0.60639211 0.18977126]]
4.187619542292837
0.15708586187171092
0.5234524427866046
[1.15597431 0.86269242 1.09391049 1.07504232]
[2.93025766 1.25736188]


In [21]:
#矩阵基本操作
A = np.arange(2, 14).reshape((3,4))
print(A)
print(np.argmin(A))
print(np.argmax(A))
print(np.mean(A))
print(np.average(A))
print(A.mean())
print(np.median(A))
print(np.cumsum(A))
print(np.diff(A))

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11
7.5
7.5
7.5
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [22]:
A = np.arange(14, 2, -1).reshape((3,4))
print(A)
print(np.sort(A))
print(np.transpose(A))
print(A.T)
print(A)
print(np.clip(A,5, 9))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


In [23]:
#数组切片
A = np.arange(3, 15)
B = A.reshape(3, 4)
B[2]
B[0][2]
B[1,1:3]
B[0:2, 1:3]
for row in B:
    print(row)

for column in B.T:
    print(column)
A = np.arange(3, 15).reshape((3, 4))
A.flatten()

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
#数组合并
A = np.array([1,1,1])
B = np.array([2,2,2])
print(np.vstack((A,B)))
print(np.hstack((A,B)))
b = np.array([[0,1,2,3,4,5],[6,7,8,9,10,11]])
c = b*2
print(np.dstack((b,c)))

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]
[[[ 0  0]
  [ 1  2]
  [ 2  4]
  [ 3  6]
  [ 4  8]
  [ 5 10]]

 [[ 6 12]
  [ 7 14]
  [ 8 16]
  [ 9 18]
  [10 20]
  [11 22]]]


In [28]:
#构造矩阵
A = np.arange(12).reshape(3,4)
print(A)
print(np.hsplit(A,2))
print(np.split(A,2,axis=1))
print(np.vsplit(A,3))
print(np.split(A,3,axis=0))
b = np.array([[0,1,2,3,4,5],[6,7,8,9,10,11]])
c = b*2
arr_dstack = np.dstack((b,c))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
